#!/bin/bash -eu

################################################################################
# The directory holding your source code and Cabal file:
SRC_DIR=~/.xmonad

################################################################################
# The name of the executable produced by cabal.  This comes from the
# executable section of your Cabal file.
EXE_NAME=xmonad-config

################################################################################
# This script will be given a single argument, the path to the
# executable it should produce.
OUT_FILE=~/.cabal/bin/xmonad

################################################################################
cd $SRC_DIR
cabal build
find dist-newstyle -type f -executable -name $EXE_NAME \
     -exec mv -u '{}' $OUT_FILE ';'
