#!/bin/bash

echo "Adding PPA to allow install of Synapse on Trusty"
sudo apt-add-repository ppa:synapse-core/testing
sudo apt-get update

echo "Installing required packages..."
sudo apt-get install xmonad libghc-xmonad-dev libghc-xmonad-contrib-dev xmobar \
    xcompmgr nitrogen stalonetray moreutils consolekit synapse xbacklight \
    ssh-askpass-gnome thunar terminator remmina conky dzen2 slock trayer xcape

echo "Creating xmonad xsession configuration..."
sudo mv /usr/share/xsessions/xmonad.desktop /usr/share/xsessions/xmonad.desktop.original
sudo cp ~/.xmonad/xmonad.desktop /usr/share/xsessions
sudo chmod a+r /usr/share/xsessions/xmonad.desktop
sudo cp ~/.xmonad/images/custom_xmonad_badge.png /usr/share/unity-greeter
sudo chmod a+r /usr/share/unity-greeter/custom_xmonad_badge.png

echo "Linking to customized gnome 2 configuration..."
mv ~/.gtkrc-2.0 ~/gtkrc-2.0.original
ln -s ~/git/.dotfiles/.xmonad/.gtkrc-2.0 ~/.gtkrc-2.0

