#!/bin/bash

source ~/.zshrc
echo "ZSH run"

start_app "thunderbird"
start_app "slack"
start_app "nm-applet --sm-disable"
start_app "synapse -s"
echo "Apps started"

setup_screens
echo "Screens setup"
